parameters:
    database_driver: pdo_pgsql
    database_host: 127.0.0.1
    database_port: null
    database_name: symf_gis
    database_user: moac
    database_password: moac8367
    mailer_transport: smtp
    mailer_host: smtp.gmail.com
    mailer_user: nhc.cuse@gmail.com
    mailer_password: ^ac/{}ps9
    locale: en
    secret: 8fd9d09938082c0c8b18687b977934e7cd2436d1
    database_path: null