igis_homepage:
    pattern:  /admin/
    defaults: { _controller: HaiiIgisBundle:Default:index }

login_check:
    pattern:  /logincheck/
    defaults: { _controller: HaiiIgisBundle:Security:loginCheck }